services:
  joinmarket-analyzer:
    image: ghcr.io/m0wer/joinmarket_analyzer:master
    build:
      context: .
      dockerfile: Dockerfile
    container_name: joinmarket-analyzer
    command: ["--help"]
